### ISSUE TITLE
better documentation

### ISSUE THREAD

**Issue by CARocha** [pyutil/django-admin-autocomplete-all#1]
Hi, the documentation is poor and confusing, you should use readthedoc.io

Cheers

**Comment by pyutil** [comment]
Thank you. So, do you want to be a volunteer here? Just describe what is confusing, I will explain it here and you can fork the repo and improve the docs/*.rst files, because at least you speak better english as me.

**Comment by pyutil** [comment]
And ... did you have success in at least the basic level, ie. if you inherit from autocomplete_all classes (instead of django native ModelAdmin or Inlines) then you will get autocompleting everywhere?
Of course you must meet the conditions from Django docs for all the foreignkeys in your model.

**Comment by CARocha** [comment]
Hi, my English is not so good, I am from Central America and my native language is Spanish, but if I can help with anything for me it is fine.
First: it would be to compose the README that is confusing the way it looks.
Second: Understand how the project works and then explain in more detail how people should do to apply them to their projects.

so if I can help you in the documentation it would be fine for me.

Now I make the fork and then throw the PR

Cheers
